export interface FlightDb {
    IdVolo: number,
    Aereo: number,
    Rotta: number,
    DataPartenzaPrev: string,
    DataArrivoPrev: string,
    DataPartenzaEff: null,
    DataArrivoEff: null,
    Stato: string,
    CostoPC: number,
    CostoB: number,
    CostoE: number,
    CostoBag: number,
    CostoLegRoom: number,
    CostoSceltaPosto: number,
    IsActive: null,
    NomePartenza: string,
    CittaPartenza: string,
    CodicePartenza: string,
    NomeArrivo: string,
    CittaArrivo: string,
    CodiceArrivo: string
}